### PR TITLE
Minimise over cells instead of over jets

### PR DESCRIPTION
**Pull request by fwyzard**
Cache the minimum distance found in each cell,  and use that to speed up the minimisation.

GPU  | `master` | `minimise_over_cells`
---|---|---
GeForce GTX 960M (sm 5.0) | 20.2 ms | 15.5 ms
Testa T4 (sm 7.5) | 14.7 ms | 10.8 ms
Tesla V100 (sm 7.0) | 7.2 ms | 7.0 ms

Timing is measured on the `data/808_cms.dat` event, running the anti-KT algorithm with a radius of 0.4 and averaging over 100 measurements. The best of 3 runs is reported.

### CODE REVIEW

**Comment by asubah** [comment]
Thanks,

I tested the branch and it didn't produce the correct number of jets for 8 events out of 3262 events.
For example this event (/afs/cern.ch/user/a/abmohame/public/hltAK4CaloJets_32617273.dat) should produce 157 jets, however it produces 156.

In all the 8 cases the branch is off by one less jet.

**Comment by fwyzard** [comment]
Thanks for the checks; I will look into it.

**Comment by fwyzard** [comment]
@asubah does it mean that you got the correct results this time ?

**Comment by asubah** [comment]
@fwyzard No, I merged it and fixed it in another pull request.
I don't think this is the correct way of doing it, but it was the easy way.

**Comment by fwyzard** [comment]
That's fine, I was just wondering what was the fix !

**Pull request merged**
